import { useEffect, useMemo, useRef, useState, type CSSProperties, type KeyboardEvent, type PointerEvent, type WheelEvent } from 'react';
import type { MetaCompContext } from '../core/types.js';
import type { Parameter } from '../core/parameter.js';
import { ControlRegistry } from '../core/registry.js';
import { keyboardStep } from '../interaction/drag.js';
import { velocityPrecision } from '../motion/physics.js';
import { resolveMetaCompPresentation } from '../layout/adaptive.js';
import { useParameterValue } from './hooks.js';
import { MetaCompFrame, MetaCompLabel, TickField } from './meta-comp.js';

const clamp=(v:number,a:number,b:number)=>Math.min(b,Math.max(a,v));
const cssNumber=(name:string,fallback:number)=>{if(typeof document==='undefined')return fallback;const v=parseFloat(getComputedStyle(document.documentElement).getPropertyValue(name));return Number.isFinite(v)?v:fallback};
function ratio(parameter:Parameter,value:unknown=parameter.value){if(parameter.min==null||parameter.max==null||parameter.max===parameter.min)return .5;return clamp((Number(value)-parameter.min)/(parameter.max-parameter.min),0,1)}
export function formatParameterValue(parameter:Parameter,value:unknown=parameter.value){if(typeof parameter.meta?.format==='function')return parameter.meta.format(value,parameter);if(parameter.type==='number'||parameter.type==='integer'){const step=parameter.step??.01,decimals=parameter.type==='integer'?0:Math.min(4,Math.max(0,String(step).split('.')[1]?.length??2));return`${Number(value).toFixed(decimals)}${parameter.unit?` ${parameter.unit}`:''}`}if(parameter.type==='range'&&Array.isArray(value))return`${value[0]} — ${value[1]}${parameter.unit?` ${parameter.unit}`:''}`;if(parameter.type==='boolean')return value?'ON':'OFF';return String(value)}

export interface ControlProps { parameter:Parameter<any>; context?:MetaCompContext; className?:string }

export function SliderControl({parameter,context={}}:ControlProps){
  const value=useParameterValue(parameter),rootRef=useRef<HTMLDivElement|null>(null),drag=useRef<any>(null);
  const min=parameter.min??0,max=parameter.max??1,span=max-min,t=ratio(parameter,value);
  const setValue=(next:number,source='pointer')=>parameter.set(min+clamp((next-min)/Math.max(.000001,span),0,1)*span,{source});
  const down=(e:PointerEvent<HTMLDivElement>)=>{if(e.button!==0||parameter.disabled||parameter.readonly)return;const root=e.currentTarget,rect=root.getBoundingClientRect(),startT=ratio(parameter),now=performance.now();drag.current={id:e.pointerId,rect,startX:e.clientX,startY:e.clientY,startT,lastX:e.clientX,lastTime:now};root.setPointerCapture?.(e.pointerId);root.dataset.interacting='true';root.focus({preventScroll:true});parameter.set(min+clamp((e.clientX-rect.left)/rect.width,0,1)*span,{source:'pointer'});e.preventDefault()};
  const move=(e:PointerEvent<HTMLDivElement>)=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;const now=performance.now(),dt=Math.max(1,now-d.lastTime),vx=(e.clientX-d.lastX)/dt*1000;d.lastX=e.clientX;d.lastTime=now;const offAxis=Math.abs(e.clientY-d.startY),offAxisDistance=cssNumber('--au-offaxis-distance',42),precisionFactor=cssNumber('--au-precision-factor',.16);const precision=Math.min(1,velocityPrecision(vx,{min:.28})*(e.altKey?precisionFactor:1)*(offAxis>12?Math.max(.08,1/(1+offAxis/offAxisDistance)):1));const nextT=offAxis>12||e.altKey?d.startT+((e.clientX-d.startX)/d.rect.width)*precision:(e.clientX-d.rect.left)/d.rect.width;e.currentTarget.style.setProperty('--au-drag-energy',String(Math.min(1,Math.abs(vx)/1400)));e.currentTarget.dataset.precision=String(precision<.72);parameter.set(min+clamp(nextT,0,1)*span,{source:precision<.72?'precision':'pointer'})};
  const end=(e:PointerEvent<HTMLDivElement>)=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;drag.current=null;delete e.currentTarget.dataset.interacting;delete e.currentTarget.dataset.precision;e.currentTarget.style.removeProperty('--au-drag-energy');e.currentTarget.releasePointerCapture?.(e.pointerId)};
  const key=(e:KeyboardEvent<HTMLDivElement>)=>{if(keyboardStep(parameter,e)){e.preventDefault();e.stopPropagation()}};
  const wheel=(e:WheelEvent<HTMLDivElement>)=>{if(parameter.disabled||parameter.readonly||(!e.shiftKey&&document.activeElement!==e.currentTarget))return;e.preventDefault();const step=parameter.step??span/100;parameter.set(Number(value)+(e.deltaY<0?step:-step),{source:'wheel'})};
  return <MetaCompFrame parameter={parameter} context={context} className="au-slider" role="slider" tabIndex={parameter.disabled?-1:0} style={{'--au-ratio':`${t*100}%`} as CSSProperties} onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onDoubleClick={()=>parameter.reset({source:'reset'})} onKeyDown={key} onWheel={wheel}>
    <MetaCompLabel parameter={parameter}/><span className="au-seam"/><output className="au-value">{formatParameterValue(parameter,value)}</output><TickField parameter={parameter}/>
  </MetaCompFrame>
}

export function RangeControl({parameter,context={}}:ControlProps){
  const value=useParameterValue(parameter) as number[],drag=useRef<any>(null);const min=parameter.min??0,max=parameter.max??1,span=max-min,[a,b]=value;const ra=ratio(parameter,a),rb=ratio(parameter,b);
  const down=(e:PointerEvent<HTMLDivElement>)=>{if(e.button!==0||parameter.disabled||parameter.readonly)return;const rect=e.currentTarget.getBoundingClientRect(),t=clamp((e.clientX-rect.left)/rect.width,0,1),threshold=18/rect.width;let mode:string;if(Math.abs(t-ra)<=threshold)mode='a';else if(Math.abs(t-rb)<=threshold)mode='b';else if(t>ra&&t<rb)mode='span';else mode=Math.abs(t-ra)<Math.abs(t-rb)?'a':'b';drag.current={id:e.pointerId,rect,startX:e.clientX,startY:e.clientY,start:[a,b],mode};e.currentTarget.setPointerCapture?.(e.pointerId);e.currentTarget.dataset.interacting='true';e.currentTarget.dataset.rangeMode=mode;e.currentTarget.focus({preventScroll:true});e.preventDefault()};
  const move=(e:PointerEvent<HTMLDivElement>)=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;const dx=(e.clientX-d.startX)/d.rect.width*span,offAxisDistance=cssNumber('--au-offaxis-distance',42),precisionFactor=cssNumber('--au-precision-factor',.15),precision=(e.altKey?precisionFactor:1)*(Math.abs(e.clientY-d.startY)>12?Math.max(.08,1/(1+Math.abs(e.clientY-d.startY)/offAxisDistance)):1);let[na,nb]=d.start as number[];const delta=dx*precision;if(d.mode==='a')na=Math.min(nb,na+delta);else if(d.mode==='b')nb=Math.max(na,nb+delta);else{const width=nb-na;na=clamp(na+delta,min,max-width);nb=na+width}parameter.set([clamp(na,min,max),clamp(nb,min,max)],{source:precision<.72?'precision':'pointer'})};
  const end=(e:PointerEvent<HTMLDivElement>)=>{if(!drag.current||drag.current.id!==e.pointerId)return;drag.current=null;delete e.currentTarget.dataset.interacting;delete e.currentTarget.dataset.rangeMode;e.currentTarget.releasePointerCapture?.(e.pointerId)};
  const key=(e:KeyboardEvent<HTMLDivElement>)=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const step=(parameter.step??span/100)*(e.shiftKey ? 10 : e.altKey ? .1 : 1),dir=e.key==='ArrowRight'||e.key==='ArrowUp'?1:-1;parameter.set([clamp(a+dir*step,min,b),b],{source:'keyboard'})};
  return <MetaCompFrame parameter={parameter} context={context} className="au-range" role="slider" tabIndex={parameter.disabled?-1:0} style={{'--au-min-ratio':`${ra*100}%`,'--au-max-ratio':`${rb*100}%`} as CSSProperties} onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onKeyDown={key} onDoubleClick={()=>parameter.reset({source:'reset'})}>
    <MetaCompLabel parameter={parameter}/><span className="au-seam au-seam-a"/><span className="au-seam au-seam-b"/><output className="au-value">{formatParameterValue(parameter,value)}</output><TickField parameter={parameter}/>
  </MetaCompFrame>
}

export function ScrubberControl({parameter,context={}}:ControlProps){
  const value=useParameterValue(parameter),drag=useRef<any>(null),span=(parameter.max??100)-(parameter.min??0);
  const down=(e:PointerEvent<HTMLDivElement>)=>{if(parameter.disabled||parameter.readonly)return;drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,start:Number(value),lastX:e.clientX,lastT:performance.now()};e.currentTarget.setPointerCapture?.(e.pointerId);e.currentTarget.dataset.interacting='true'};
  const move=(e:PointerEvent<HTMLDivElement>)=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;const now=performance.now(),vx=(e.clientX-d.lastX)/Math.max(1,now-d.lastT)*1000;d.lastX=e.clientX;d.lastT=now;const off=Math.abs(e.clientY-d.y),precision=(e.altKey?cssNumber('--au-precision-factor',.1):1)*Math.max(.08,1/(1+off/cssNumber('--au-offaxis-distance',44)))*velocityPrecision(vx,{min:.35});parameter.set(d.start+(e.clientX-d.x)*span/240*precision,{source:precision<.72?'precision':'pointer'});e.currentTarget.dataset.precision=String(precision<.72)};
  const end=(e:PointerEvent<HTMLDivElement>)=>{if(!drag.current||drag.current.id!==e.pointerId)return;drag.current=null;delete e.currentTarget.dataset.interacting;delete e.currentTarget.dataset.precision;e.currentTarget.releasePointerCapture?.(e.pointerId)};
  return <MetaCompFrame parameter={parameter} context={context} className="au-scrubber" role="slider" tabIndex={0} onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onKeyDown={e=>{if(keyboardStep(parameter,e))e.preventDefault()}} onDoubleClick={()=>parameter.reset({source:'reset'})}><MetaCompLabel parameter={parameter}/><output className="au-value">{formatParameterValue(parameter,value)}</output></MetaCompFrame>
}

export function NumberControl({parameter,context={}}:ControlProps){const value=useParameterValue(parameter);return <MetaCompFrame parameter={parameter} context={context} className="au-number"><MetaCompLabel parameter={parameter}/><input className="au-number-surface" type="number" value={String(value)} min={parameter.min} max={parameter.max} step={parameter.step??.01} aria-label={parameter.label} onChange={e=>parameter.set(Number(e.currentTarget.value),{source:'keyboard'})} onKeyDown={e=>{if(keyboardStep(parameter,e)){e.preventDefault();e.stopPropagation()}}}/></MetaCompFrame>}

export function ToggleControl({parameter,context={}}:ControlProps){const value=Boolean(useParameterValue(parameter));return <MetaCompFrame parameter={parameter} context={context} className={`au-toggle ${value?'is-on':'is-off'}`} style={{'--au-toggle-index':value?1:0} as CSSProperties}><MetaCompLabel parameter={parameter}/><button type="button" className="au-toggle-surface" aria-pressed={value} onClick={()=>parameter.set(!value,{source:'pointer'})}><span className="au-state-material" style={{transform:value?'translateX(calc(100% - 3px))':undefined}}/><span>OFF</span><span>ON</span></button></MetaCompFrame>}

export function SegmentedControl({parameter,context={}}:ControlProps){const value=useParameterValue(parameter),options=(parameter.options??[]) as unknown[],index=Math.max(0,options.findIndex(v=>Object.is(v,value)));return <MetaCompFrame parameter={parameter} context={context} className="au-segmented" style={{'--au-segment-count':options.length||1,'--au-segment-index':index} as CSSProperties}><MetaCompLabel parameter={parameter}/><div className="au-segment-surface" role="radiogroup" aria-label={parameter.label}><span className="au-segment-material"/>{options.map(option=><button key={String(option)} type="button" role="radio" aria-checked={Object.is(option,value)} className={Object.is(option,value)?'active':''} onClick={()=>parameter.set(option,{source:'pointer'})}>{String(option)}</button>)}</div></MetaCompFrame>}

export function SelectControl({parameter,context={}}:ControlProps){const value=useParameterValue(parameter),options=(parameter.options??[]) as unknown[],[open,setOpen]=useState(false),root=useRef<HTMLDivElement|null>(null);useEffect(()=>{if(!open)return;const onDown=(e:globalThis.PointerEvent)=>{if(root.current&&!root.current.contains(e.target as Node))setOpen(false)};const onKey=(e:globalThis.KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};addEventListener('pointerdown',onDown);addEventListener('keydown',onKey);return()=>{removeEventListener('pointerdown',onDown);removeEventListener('keydown',onKey)}},[open]);return <div ref={root}><MetaCompFrame parameter={parameter} context={context} className="au-select"><MetaCompLabel parameter={parameter}/><button type="button" className="au-select-trigger" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{String(value)}</button>{open?<div className="au-select-menu" role="listbox">{options.map(option=><button key={String(option)} type="button" className="au-select-option" aria-selected={Object.is(option,value)} onClick={()=>{parameter.set(option,{source:'pointer'});setOpen(false)}}>{String(option)}</button>)}</div>:null}</MetaCompFrame></div>}

export function TextControl({parameter,context={}}:ControlProps){const value=String(useParameterValue(parameter)??'');return <MetaCompFrame parameter={parameter} context={context} className="au-text"><MetaCompLabel parameter={parameter}/><input className="au-text-surface" type="text" value={value} aria-label={parameter.label} onChange={e=>parameter.set(e.currentTarget.value,{source:'keyboard'})}/></MetaCompFrame>}

export function ColorControl({parameter,context={}}:ControlProps){const value=String(useParameterValue(parameter));return <MetaCompFrame parameter={parameter} context={context} className="au-color" style={{'--au-color-value':value} as CSSProperties}><MetaCompLabel parameter={parameter}/><input className="au-color-input" type="color" value={value} aria-label={parameter.label} onChange={e=>parameter.set(e.currentTarget.value,{source:'pointer'})}/><output className="au-value">{value.toUpperCase()}</output></MetaCompFrame>}

export function GradientControl({parameter,context={}}:ControlProps){const value=(useParameterValue(parameter) as string[])??['#000000','#ffffff'];return <MetaCompFrame parameter={parameter} context={context} className="au-gradient"><MetaCompLabel parameter={parameter}/><div className="au-gradient-surface" style={{background:`linear-gradient(90deg,${value.join(',')})`}}>{value.slice(0,4).map((color,i)=><input key={i} type="color" value={color} aria-label={`${parameter.label} stop ${i+1}`} onChange={e=>{const next=[...value];next[i]=e.currentTarget.value;parameter.set(next,{source:'pointer'})}}/>)}</div></MetaCompFrame>}

export function VectorControl({parameter,context={}}:ControlProps){const value=(useParameterValue(parameter) as number[])??[0,0,0],axes=['X','Y','Z','W'].slice(0,value.length);return <MetaCompFrame parameter={parameter} context={context} className="au-vector"><MetaCompLabel parameter={parameter}/><div className="au-vector-surface">{axes.map((axis,i)=><label key={axis} className="au-vector-axis"><b>{axis}</b><input type="number" step={parameter.step??.01} value={value[i]??0} aria-label={`${parameter.label} ${axis}`} onChange={e=>{const next=[...value];next[i]=Number(e.currentTarget.value);parameter.set(next,{source:'keyboard'})}}/></label>)}</div></MetaCompFrame>}

export function XYControl({parameter,context={}}:ControlProps){const value=(useParameterValue(parameter) as number[])??[0,0],drag=useRef<number|null>(null),min=parameter.min??0,max=parameter.max??1,rx=ratio(parameter,value[0]),ry=1-ratio(parameter,value[1]);const write=(e:PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width,0,1),y=1-clamp((e.clientY-r.top)/r.height,0,1);parameter.set([min+x*(max-min),min+y*(max-min)],{source:'pointer'})};return <MetaCompFrame parameter={parameter} context={context} className="au-xy"><MetaCompLabel parameter={parameter}/><div className="au-xy-surface" tabIndex={0} role="application" aria-label={parameter.label} onPointerDown={e=>{drag.current=e.pointerId;e.currentTarget.setPointerCapture?.(e.pointerId);write(e)}} onPointerMove={e=>{if(drag.current===e.pointerId)write(e)}} onPointerUp={e=>{if(drag.current===e.pointerId){drag.current=null;e.currentTarget.releasePointerCapture?.(e.pointerId)}}} onPointerCancel={()=>{drag.current=null}}><i className="au-xy-dot" style={{left:`${rx*100}%`,top:`${ry*100}%`}}/></div><output className="au-value">{`${Number(value[0]).toFixed(2)} · ${Number(value[1]).toFixed(2)}`}</output></MetaCompFrame>}

export function MeterControl({parameter,context={}}:ControlProps){const value=useParameterValue(parameter),t=ratio(parameter,value);return <MetaCompFrame parameter={parameter} context={context} className="au-meter" style={{'--au-ratio':`${t*100}%`} as CSSProperties}><MetaCompLabel parameter={parameter}/><span className="au-meter-bars"/><output className="au-value">{formatParameterValue(parameter,value)}</output></MetaCompFrame>}

export function KnobControl({parameter,context={}}:ControlProps){const value=useParameterValue(parameter),t=ratio(parameter,value),drag=useRef<any>(null);return <MetaCompFrame parameter={parameter} context={context} className="au-knob"><MetaCompLabel parameter={parameter}/><div className="au-knob-surface" tabIndex={0} role="slider" aria-label={parameter.label} style={{'--au-knob-angle':`${-135+t*270}deg`,'--au-knob-progress':`${t*75}%`} as CSSProperties} onPointerDown={e=>{drag.current={id:e.pointerId,y:e.clientY,start:Number(value)};e.currentTarget.setPointerCapture?.(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;const span=(parameter.max??1)-(parameter.min??0);parameter.set(d.start+(d.y-e.clientY)*span/160*(e.altKey?.15:1),{source:e.altKey?'precision':'pointer'})}} onPointerUp={e=>{drag.current=null;e.currentTarget.releasePointerCapture?.(e.pointerId)}}/><output className="au-value">{formatParameterValue(parameter,value)}</output></MetaCompFrame>}

export function ActionControl({parameter,context={}}:ControlProps){return <MetaCompFrame parameter={parameter} context={context} className="au-action"><button type="button" className="au-action-surface" onClick={()=>{if(typeof parameter.meta?.action==='function')parameter.meta.action(parameter);parameter.graph.events.emit('action',{parameter})}}>{parameter.label}</button></MetaCompFrame>}

export const defaultControlRegistry=new ControlRegistry();
export function registerDefaultControls(registry=defaultControlRegistry){const registrations:Array<[string,string,any,number]>=[['number','slider',SliderControl,10],['number','number',NumberControl,1],['number','scrubber',ScrubberControl,2],['number','meter',MeterControl,1],['number','knob',KnobControl,1],['integer','slider',SliderControl,10],['integer','number',NumberControl,1],['integer','scrubber',ScrubberControl,2],['boolean','toggle',ToggleControl,10],['enum','segmented',SegmentedControl,10],['enum','select',SelectControl,5],['string','text',TextControl,10],['color','color',ColorControl,10],['range','range',RangeControl,10],['vec2','xy',XYControl,10],['vec2','vector',VectorControl,5],['vec3','vector',VectorControl,10],['vec4','vector',VectorControl,10],['gradient','gradient',GradientControl,10],['action','button',ActionControl,10]];for(const[type,presentation,component,priority]of registrations)registry.register(type,presentation,component,{priority});return registry}
registerDefaultControls();

export function Control({parameter,context={},registry=defaultControlRegistry}:ControlProps&{registry?:ControlRegistry}){const presentation=resolveMetaCompPresentation(parameter,context),resolved=registry.resolve(parameter,{...context,presentation});if(!resolved)return <TextControl parameter={parameter} context={context}/>;const Component=resolved.component;return <Component parameter={parameter} context={{...context,presentation:resolved.presentation}}/>}

export function Button({children,onClick,className='',type='button',disabled=false}:{children:any;onClick?:()=>void;className?:string;type?:'button'|'submit'|'reset';disabled?:boolean}){return <button type={type} className={`au-button ${className}`.trim()} onClick={onClick} disabled={disabled}>{children}</button>}
export function TextArea(props:any){return <textarea {...props} className={`au-textarea ${props.className??''}`.trim()}/>}
