import type { MetaCompContext } from '../core/types.js';
import type { Parameter } from '../core/parameter.js';
export const densityProfiles = Object.freeze({
  micro:{controlHeight:24,labelMode:'contextual',secondary:false,hitMin:28,valueMode:'compact'},
  compact:{controlHeight:28,labelMode:'external',secondary:true,hitMin:32,valueMode:'inline'},
  full:{controlHeight:32,labelMode:'external',secondary:true,hitMin:34,valueMode:'inline'},
  touch:{controlHeight:42,labelMode:'stacked',secondary:true,hitMin:44,valueMode:'inline'},
  focus:{controlHeight:48,labelMode:'stacked',secondary:true,hitMin:48,valueMode:'expanded'}
});
export function resolveDensity({width=Infinity,height=Infinity,modality='pointer',preference='auto',importance=0}:MetaCompContext={}){
  if(preference!=='auto')return String(preference); if(modality==='touch')return width<460||height<280?'focus':'touch'; if(width<165)return importance>.65?'compact':'micro'; if(width<300)return'compact'; return'full';
}
export function resolveLabelMode({width=Infinity,density='full',requested=null,importance=0}:{width?:number;density?:string;requested?:string|null;importance?:number}={}){if(requested)return requested;if(density==='micro')return width<145&&importance<.6?'contextual':'integrated';if(density==='touch'||density==='focus')return'stacked';if(width<245)return'integrated';return'external'}
export function resolveMetaCompPresentation(parameter:Parameter,context:MetaCompContext={}){const density=String(context.density??resolveDensity({...context,importance:Number(parameter.meta?.importance??0)}));const type=parameter.type;const requested=context.presentation??parameter.presentation;if(requested)return String(requested);if(density==='micro'){if(type==='number'||type==='integer')return parameter.meta?.continuous===false?'number':'scrubber';if(type==='enum')return(parameter.options?.length??0)<=3?'segmented':'select';if(['vec2','vec3','vec4'].includes(type))return'vector'}if(density==='touch'||density==='focus'){if(type==='number'||type==='integer')return'slider';if(type==='vec2')return'xy';if(type==='enum')return(parameter.options?.length??0)<=4?'segmented':'select'}return({number:'slider',integer:'slider',boolean:'toggle',enum:'segmented',color:'color',range:'range',vec2:'xy',vec3:'vector',vec4:'vector',gradient:'gradient',action:'button'} as Record<string,string>)[type]??'text'}
export function resolveMetaCompContext(parameter:Parameter,context:MetaCompContext={}){const importance=Number(context.importance??parameter.meta?.importance??(parameter.meta?.emphasis==='hero'?.8:.35));const density=String(context.density??resolveDensity({...context,importance}));const profile=(densityProfiles as Record<string,any>)[density]??densityProfiles.full;const labelMode=resolveLabelMode({width:context.width,density,requested:String(context.labelMode??parameter.meta?.labelMode??'')||null,importance});return{...profile,...context,density,presentation:resolveMetaCompPresentation(parameter,{...context,density}),emphasis:String(context.emphasis??parameter.meta?.emphasis??'standard'),labelMode,importance,compact:density==='micro'||density==='compact'}}
export function negotiateLayout<T extends {importance?:number;ideal?:number;min?:number;max?:number}>(items:T[],available:number,{gap=0}={}){const result:Array<T&{size:number;visible:boolean}>=[];let remaining=available;const sorted=[...items].sort((a,b)=>(b.importance??0)-(a.importance??0));for(const item of sorted){const ideal=item.ideal??item.min??0,min=item.min??0,max=item.max??Infinity,usable=Math.max(0,remaining-(result.length?gap:0)),size=Math.max(0,Math.min(max,ideal,usable));if(size>=min){if(result.length)remaining-=gap;result.push({...item,size,visible:true});remaining-=size}else result.push({...item,size:0,visible:false})}return result}
export function resolveResponsivePosture({width=Infinity,height=Infinity,role='panel'}:{width?:number;height?:number;role?:string}={}){const aspect=width&&height?width/height:1;if(width<520)return role==='timeline'?'bottom-sheet':'focus';if(aspect>1.7&&role==='timeline')return'bottom';if(aspect<.9&&role==='inspector')return'right';return'embedded'}
