import assert from 'node:assert/strict';
import { ParameterGraph } from '../packages/ui/dist/core/index.js';
import { normalizeControlSchema } from '../packages/ui/dist/schema/index.js';
import { resolveDensity, resolveMetaCompPresentation } from '../packages/ui/dist/layout/index.js';
import { springStep, magneticStrength } from '../packages/ui/dist/motion/index.js';
import { themes } from '../packages/ui/dist/design/index.js';
import { componentRegistry } from '../packages/ui/dist/component/index.js';
import { MetaBlockWorkspace, dockFieldStrength, resolveDockCandidates, chooseDockCandidate, stabilizeDockCandidate, resolveDockPreviewRect, resolveWorkspaceRects, resolveKineticPose, magneticOffset } from '../packages/metablock/dist/core/index.js';

let passed=0;
const test=(name,fn)=>{try{fn();passed++;console.log(`PASS ${name}`)}catch(error){console.error(`FAIL ${name}`);throw error}};

test('ParameterGraph exact state, clamp, step, history, restore',()=>{
  const graph=new ParameterGraph();const p=graph.define({id:'material.roughness',value:.5,min:0,max:1,step:.01});p.set(2);assert.equal(p.value,1);p.set(.333);assert.equal(p.value,.33);assert.equal(graph.history.undo(),true);assert.equal(p.value,1);assert.equal(graph.history.redo(),true);assert.equal(p.value,.33);const snap=graph.serialize();p.set(.9);graph.restore(snap);assert.equal(p.value,.33);
});
test('Schema inference + adaptive MetaComp resolution',()=>{const out=normalizeControlSchema({material:{$meta:{label:'SURFACE'},roughness:{value:.5,min:0,max:1,emphasis:'hero'},enabled:true}});assert.equal(out[0].kind,'section');assert.equal(out[0].label,'SURFACE');assert.equal(resolveDensity({width:150}),'micro');assert.equal(resolveMetaCompPresentation({type:'number',presentation:null,meta:{}} ,{width:150}),'scrubber')});
test('UI motion primitives stable',()=>{const next=springStep({position:0,velocity:0},1,1/60);assert.ok(Number.isFinite(next.position));assert.equal(magneticStrength(100,50),0)});
test('Design worlds and machine readable component definitions',()=>{assert.ok(themes.glass&&themes.graphite&&themes.stone&&themes.smoke&&themes.monolith&&themes.light);assert.ok(componentRegistry.has('slider'));assert.ok(componentRegistry.get('slider').interactions.includes('off-axis-precision'))});

test('MetaBlock is the authoritative primitive and dock/panel are roles',()=>{const w=new MetaBlockWorkspace({id:'studio'});const dock=w.createGroup({id:'dock',role:'dock'});w.createMetaBlock({id:'scene',title:'Scene',role:'panel'},{groupId:dock});w.createMetaBlock({id:'material',title:'Material',role:'panel'},{groupId:dock});assert.equal(w.blocks.get('dock').role,'dock');assert.equal(w.blocks.get('scene').role,'panel');assert.deepEqual(w.groups.get('dock').children,['scene','material']);assert.equal(w.blocks.get('scene').parentId,'dock')});
test('MetaBlock child can detach, float, dock, split and merge without identity change',()=>{const w=new MetaBlockWorkspace();const dock=w.createGroup({id:'dock',role:'dock'});w.createMetaBlock({id:'scene',role:'panel'},{groupId:dock});w.createMetaBlock({id:'material',role:'panel'},{groupId:dock});const original=w.blocks.get('material');const floated=w.floatBlock('material',{x:20,y:30,width:320,height:240});assert.ok(floated);assert.strictEqual(w.blocks.get('material'),original);assert.deepEqual(w.groups.get('dock').children,['scene']);assert.equal(w.groups.get(floated).posture,'floating');w.dockBlock('material',{area:'right',size:.3});const owner=w.getBlockGroup('material');assert.ok(owner);assert.equal(owner.posture,'docked');w.mergeBlock('material','dock');assert.deepEqual(w.groups.get('dock').children,['scene','material']);assert.strictEqual(w.blocks.get('material'),original)});
test('MetaBlock zones, pin, popout, reattach, connection',()=>{const w=new MetaBlockWorkspace();const g=w.createGroup({id:'tools',role:'tool'});w.createMetaBlock({id:'p',role:'panel'},{groupId:g});const z=w.createWorkspaceZone({id:'viewport',modes:['overlay','right-dock'],adaptive:{compactWidth:600,compactMode:'overlay',balancedMode:'right-dock'}});w.placeGroupInZone(g,z,{mode:'auto'});assert.equal(w.groups.get(g).posture,'zone');w.pinGroup(g,{edge:'right',autoHide:true});assert.equal(w.groups.get(g).posture,'auto-hide');w.popoutGroup(g);assert.equal(w.groups.get(g).posture,'popout');w.reattachPopout(g,{area:'left'});assert.equal(w.groups.get(g).posture,'docked');const g2=w.createGroup({id:'peer'});w.createMetaBlock({id:'q'},{groupId:g2});assert.ok(w.connections.has(w.connectGroups(g,g2,{kind:'snap'})))});
test('Dock fields, hysteresis and landing geometry',()=>{assert.ok(dockFieldStrength(10,50)>dockFieldStrength(30,50));const candidates=resolveDockCandidates({x:4,y:100},{workspaceRect:{left:0,top:0,right:800,bottom:600},targets:[],radius:72,velocity:0});assert.equal(candidates[0].area,'left');const previous={kind:'workspace-edge',area:'right',strength:.72,distance:1};const next=chooseDockCandidate([{kind:'workspace-edge',area:'bottom',strength:.76,distance:1},{kind:'workspace-edge',area:'right',strength:.72,distance:1}],previous,{hysteresis:.1});assert.equal(next.area,'right');assert.deepEqual(resolveDockPreviewRect({kind:'workspace-edge',area:'right',strength:1,distance:0},{workspaceRect:{left:0,top:0,width:1000,height:600,right:1000,bottom:600},defaultRatio:.3}),{x:700,y:0,width:300,height:600})});
test('Dock intent gate prevents accidental weak commits',()=>{const candidate={kind:'split',targetId:'panel-b',area:'right',strength:.62,distance:4};let gate={key:null,since:0,candidate:null};gate=stabilizeDockCandidate(candidate,gate,{now:100,holdMs:72,minStrength:.46,instantStrength:.92});assert.equal(gate.candidate,null);gate=stabilizeDockCandidate(candidate,gate,{now:190,holdMs:72,minStrength:.46,instantStrength:.92});assert.equal(gate.candidate?.targetId,'panel-b');const weak=stabilizeDockCandidate({...candidate,strength:.2},gate,{now:210,holdMs:72,minStrength:.46});assert.equal(weak.candidate,null)});
test('Spatial physics returns bounded expressive pose',()=>{const source={x:100,y:100,width:300,height:220},target={x:420,y:80,width:260,height:260};const magnet=magneticOffset(source,target,.8,.75);const pose=resolveKineticPose({velocityX:900,velocityY:-250,fieldStrength:.8,magnet,motion:{profile:'expressive',stiffness:280,damping:28,mass:1,magnetism:.75,inertia:.5,response:240,compression:.012,lift:6,tilt:1.5}});assert.ok(Math.abs(pose.rotate)<=2.1);assert.ok(pose.lift>0);assert.ok(pose.field===.8);assert.ok(Number.isFinite(pose.translateX))});
test('MetaBlock layout resolver deterministic',()=>{const w=new MetaBlockWorkspace();const center=w.createGroup({id:'center'});w.createMetaBlock({id:'a'},{groupId:center});const dock=w.createGroup({id:'dock',role:'dock'});w.createMetaBlock({id:'b'},{groupId:dock});w.dockGroup(dock,{area:'bottom',size:.25});const regions=resolveWorkspaceRects(w,{width:1000,height:800,gap:0});assert.equal(Math.round(regions.get('dock').height),200);assert.equal(Math.round(regions.get('center').height),600)});
test('Locked fullscreen viewport MetaBlock stays full behind independent docks',()=>{const w=new MetaBlockWorkspace();const viewport=w.createGroup({id:'viewport',role:'viewport',posture:'fullscreen-locked',lockedFullscreen:true});w.createMetaBlock({id:'view',role:'viewport'},{groupId:viewport});const dock=w.createGroup({id:'dock',role:'dock'});w.createMetaBlock({id:'tools',role:'panel'},{groupId:dock});w.dockGroup(dock,{area:'bottom',size:.25});const regions=resolveWorkspaceRects(w,{width:1000,height:800,gap:8});assert.deepEqual(regions.get('viewport'),{x:0,y:0,width:1000,height:800,left:0,top:0,right:1000,bottom:800});assert.ok((regions.get('dock')?.height??0)>190);assert.equal(w.floatGroup(viewport),false)});
test('Workspace serialization uses blocks as canonical persistence',()=>{const w=new MetaBlockWorkspace({id:'persist'});const g=w.createGroup({id:'dock',role:'dock'});w.createMetaBlock({id:'scene',role:'panel'},{groupId:g});const snap=w.serialize();assert.ok(Array.isArray(snap.blocks));assert.equal(snap.panels,undefined);const w2=new MetaBlockWorkspace();w2.restore(snap);assert.equal(w2.blocks.get('scene').parentId,'dock');assert.deepEqual(w2.groups.get('dock').children,['scene'])});

test('Detached MetaBlock gets neutral spatial root and can pin/popout as one block',()=>{const w=new MetaBlockWorkspace();const dock=w.createGroup({id:'dock',role:'dock',meta:{variant:'command-surface',zoneSize:.4}});w.createMetaBlock({id:'material',role:'panel',meta:{preferredFloatingSize:{width:410,height:300}}},{groupId:dock});w.createMetaBlock({id:'render',role:'panel'},{groupId:dock});const floated=w.floatBlock('material',{x:40,y:50,width:410,height:300});assert.ok(floated);const root=w.groups.get(floated);assert.equal(root.role,'panel');assert.equal(root.meta.variant,undefined);assert.equal(root.children[0],'material');assert.equal(w.pinBlock('material',{edge:'right'}),floated);assert.equal(w.groups.get(floated).posture,'pinned');assert.equal(w.popoutBlock('material',{x:10,y:10,width:500,height:320}),floated);assert.equal(w.groups.get(floated).posture,'popout')});
test('Removing a regrouped split target rewires dependent layout nodes',()=>{const w=new MetaBlockWorkspace();const a=w.createGroup({id:'a'}),b=w.createGroup({id:'b'}),c=w.createGroup({id:'c'});w.createMetaBlock({id:'ba'},{groupId:a});w.createMetaBlock({id:'bb'},{groupId:b});w.createMetaBlock({id:'bc'},{groupId:c});w.dockGroup(b,{area:'right',targetGroupId:a,size:.3});w.dockGroup(c,{area:'bottom',targetGroupId:b,size:.3});w.mergeGroups(b,a);const cNode=w.layout.find(n=>n.groupId===c);assert.ok(cNode);assert.notEqual(cNode.targetGroupId,'b');const regions=resolveWorkspaceRects(w,{width:900,height:600,gap:8});assert.ok(regions.get('a'));assert.ok(regions.get('c'));assert.ok((regions.get('c')?.width??0)<900||(regions.get('c')?.height??0)<600)});
test('Detached MetaBlock remembers exact home group and tab index',()=>{const w=new MetaBlockWorkspace();const dock=w.createGroup({id:'dock',role:'dock'});w.createMetaBlock({id:'scene',role:'panel'},{groupId:dock});w.createMetaBlock({id:'material',role:'panel'},{groupId:dock});w.createMetaBlock({id:'render',role:'panel'},{groupId:dock});const floated=w.floatBlock('material',{x:50,y:60,width:420,height:300});assert.ok(floated);const home=w.getBlockReturnState('material');assert.equal(home?.sourceGroupId,'dock');assert.equal(home?.sourceIndex,1);assert.deepEqual(w.groups.get('dock').children,['scene','render']);assert.equal(w.returnBlock('material'),'dock');assert.deepEqual(w.groups.get('dock').children,['scene','material','render']);assert.equal(w.getBlockReturnState('material'),null)});
test('One-child dock remains a persistent parent while its child floats and returns',()=>{const w=new MetaBlockWorkspace();const dock=w.createGroup({id:'dock',role:'dock',title:'Command Dock',meta:{persistentContainer:true}});w.createMetaBlock({id:'material',role:'panel'},{groupId:dock});w.dockGroup(dock,{area:'bottom',size:.31});const floating=w.floatBlock('material',{x:80,y:90,width:400,height:300});assert.ok(floating);assert.notEqual(floating,'dock');assert.equal(w.groups.get('dock')?.posture,'docked');assert.equal(w.groups.get('dock')?.role,'dock');assert.deepEqual(w.groups.get('dock')?.children,[]);assert.ok(w.getBlockReturnState('material'));assert.equal(w.returnBlock('material'),'dock');assert.equal(w.groups.get('dock')?.role,'dock');assert.equal(w.groups.get('dock')?.posture,'docked');assert.deepEqual(w.groups.get('dock')?.children,['material']);assert.equal(w.layout.find(n=>n.groupId==='dock')?.area,'bottom')});
test('Snap keeps MetaBlock floating while Dock changes structural posture',()=>{const w=new MetaBlockWorkspace();const dock=w.createGroup({id:'dock',role:'dock'});w.createMetaBlock({id:'material',role:'panel'},{groupId:dock});const floating=w.floatBlock('material',{x:100,y:100,width:360,height:260});assert.ok(floating);w.snapBlockToEdge('material','right',{workspaceWidth:1200,workspaceHeight:800,gap:10});const owner=w.getBlockGroup('material');assert.equal(owner?.posture,'floating');assert.equal(Math.round(w.floating.get(owner.id)?.x??0),830);w.dockBlock('material',{area:'right',size:.28});assert.equal(w.getBlockGroup('material')?.posture,'docked')});


test('Persistent dock MetaBlock survives when its last child detaches and accepts it back',()=>{const w=new MetaBlockWorkspace();const dock=w.createGroup({id:'dock',title:'Command Surface',role:'dock',meta:{persistentContainer:true}});w.createMetaBlock({id:'scene',role:'panel'},{groupId:dock});const floating=w.floatBlock('scene',{x:20,y:30,width:400,height:320});assert.ok(floating);assert.ok(w.groups.has('dock'));assert.equal(w.groups.get('dock').children.length,0);assert.equal(w.blocks.get('scene').parentId,floating);w.mergeBlock('scene','dock');assert.deepEqual(w.groups.get('dock').children,['scene']);assert.equal(w.blocks.get('scene').parentId,'dock')});

test('Relationship context exposes parent, siblings and return-home state',()=>{const w=new MetaBlockWorkspace();const dock=w.createGroup({id:'dock',title:'Command Surface',role:'dock',meta:{persistentContainer:true}});w.createMetaBlock({id:'scene',role:'panel'},{groupId:dock});w.createMetaBlock({id:'material',role:'panel'},{groupId:dock});let ctx=w.getBlockRelationshipContext('material');assert.equal(ctx?.isDockChild,true);assert.equal(ctx?.siblings[0]?.id,'scene');w.floatBlock('material',{x:40,y:40,width:400,height:320});ctx=w.getBlockRelationshipContext('material');assert.equal(ctx?.isDetached,true);assert.equal(ctx?.canReturnHome,true);assert.equal(ctx?.home?.sourceGroupId,'dock')});

test('Maximizing one child MetaBlock never maximizes its parent dock',()=>{const w=new MetaBlockWorkspace();const dock=w.createGroup({id:'dock',role:'dock',meta:{persistentContainer:true}});w.createMetaBlock({id:'scene',role:'panel'},{groupId:dock});w.createMetaBlock({id:'material',role:'panel'},{groupId:dock});const maximized=w.maximizeBlock('material');assert.ok(maximized);assert.notEqual(maximized,'dock');assert.equal(w.groups.get('dock').posture,'docked');assert.deepEqual(w.groups.get('dock').children,['scene']);assert.equal(w.getBlockGroup('material')?.posture,'maximized');assert.equal(w.restoreBlock('material'),'dock');assert.deepEqual(w.groups.get('dock').children,['scene','material'])});

test('Parent-aware dock candidate communicates attach intent and priority',()=>{const targets=[{id:'home',rect:{left:100,top:100,right:500,bottom:400,width:400,height:300},mergeOnly:true,priority:.16,mergeIntent:'ATTACH BACK TO PARENT',relation:'home'}];const candidates=resolveDockCandidates({x:300,y:250},{workspaceRect:{left:0,top:0,right:1000,bottom:700},targets,radius:72,velocity:0});assert.equal(candidates[0].kind,'merge');assert.equal(candidates[0].intent,'ATTACH BACK TO PARENT');assert.equal(candidates[0].relation,'home')});
test('Detached panel cannot become an accidental root-center fullscreen dock',()=>{const w=new MetaBlockWorkspace();const dock=w.createGroup({id:'dock',role:'dock',meta:{persistentContainer:true}});w.createMetaBlock({id:'material',role:'panel',meta:{preferredFloatingSize:{width:560,height:410}}},{groupId:dock});const floating=w.floatBlock('material',{x:40,y:40,width:560,height:410});assert.ok(floating);assert.equal(w.dockBlock('material',{area:'center',targetGroupId:null}),false);assert.equal(w.getBlockGroup('material')?.posture,'floating');const regions=resolveWorkspaceRects(w,{width:1200,height:800,gap:8});assert.equal(regions.has(floating),false)});

test('Legacy root-center detached panel state repairs to preferred floating geometry',()=>{const w=new MetaBlockWorkspace();const g=w.createGroup({id:'detached',role:'panel',posture:'docked',meta:{extractedBlock:true}});w.createMetaBlock({id:'material',role:'panel',meta:{preferredFloatingSize:{width:560,height:410}}},{groupId:g});w.setLayout([{id:'legacy-center',groupId:g,area:'center',targetGroupId:null,size:1,order:0}],{history:false});assert.equal(w.repairSpatialState({workspaceWidth:1200,workspaceHeight:800}),true);assert.equal(w.groups.get(g)?.posture,'floating');assert.equal(w.floating.get(g)?.width,560);assert.equal(w.floating.get(g)?.height,410)});

test('Persistent dock repairs to declared home zone instead of root layout',()=>{const w=new MetaBlockWorkspace();const zone=w.createWorkspaceZone({id:'viewport-tools',modes:['bottom-dock','left-dock','right-dock']});const dock=w.createGroup({id:'dock',role:'dock',posture:'docked',meta:{persistentContainer:true,homeZoneId:zone,homeZoneMode:'bottom-dock',lockHomeZone:true}});w.createMetaBlock({id:'scene',role:'panel'},{groupId:dock});w.setLayout([{id:'bad',groupId:dock,area:'bottom',targetGroupId:null,size:.4,order:0}],{history:false});assert.equal(w.repairSpatialState(),true);assert.equal(w.groups.get(dock)?.posture,'zone');assert.ok(w.zones.get(zone)?.groups.includes(dock));assert.equal(w.zones.get(zone)?.modeByGroup[dock],'bottom-dock')});

test('Dock target semantics prefer attachment over splitting',()=>{const dockTarget={id:'dock',rect:{left:100,top:500,right:900,bottom:760,width:800,height:260},mergeOnly:true,priority:.1,mergeIntent:'ATTACH TO DOCK',relation:'dock'};const nearEdge=resolveDockCandidates({x:106,y:620},{workspaceRect:{left:0,top:0,right:1000,bottom:800},targets:[dockTarget],radius:72,velocity:0});assert.ok(nearEdge.some(c=>c.kind==='merge'&&c.targetId==='dock'));assert.equal(nearEdge.some(c=>c.kind==='split'&&c.targetId==='dock'),false)});

test('Re-grouped panel adopts its new dock as the next return parent',()=>{const w=new MetaBlockWorkspace();const a=w.createGroup({id:'dock-a',role:'dock',meta:{persistentContainer:true}}),b=w.createGroup({id:'dock-b',role:'dock',meta:{persistentContainer:true}});w.createMetaBlock({id:'material',role:'panel'},{groupId:a});w.floatBlock('material',{x:10,y:10,width:400,height:300});assert.equal(w.getBlockReturnState('material')?.sourceGroupId,'dock-a');w.mergeBlock('material',b);assert.equal(w.getBlockReturnState('material'),null);w.floatBlock('material',{x:20,y:20,width:400,height:300});assert.equal(w.getBlockReturnState('material')?.sourceGroupId,'dock-b');assert.equal(w.returnBlock('material'),b)});
console.log(`ARTINOS core tests ${passed}/${passed} PASS`);
