import { useEffect, useMemo, useRef, useState } from 'react';
import {
  applyTheme, BrandMark, Button, ChromeBar, ChromeFill, ContextMenu, Control, Inspector, PanelTitle, SearchBox, StatusLine,
  TabBar, TelemetryStrip, syncParameterGraph, useParameterValue, type MetaCompContext, type Parameter, type SchemaEntry
} from '@artinos/ui';
import {
  MetaBlockWorkspace, MetaBlockWorkspaceView, type GroupChromeContext, type LayoutNode, type MetaBlockGroup, type MetaBlockInstance, type MetaBlockMotionConfig
} from '@artinos/metablock';
import { SYSTEM_SETTINGS_CHANNEL, SYSTEM_SETTINGS_STORAGE } from '../../shared/system-schema.js';
import { createStudioModel, type StudioPageSpec } from './studio-model.js';

const model=createStudioModel();
const {graph,workspace,pageSpecs,quickEntries,ids}=model;
function useValue<T=any>(id:string){const parameter=graph.get<T>(id);if(!parameter)throw new Error(`Missing parameter ${id}`);return useParameterValue(parameter)}
function controlEntries(entries:SchemaEntry[]){return entries.filter((entry):entry is any=>entry.kind==='control')}
function useSpatialMotion():Partial<MetaBlockMotionConfig>{return{profile:String(useValue('system.motion.profile')).toLowerCase(),stiffness:Number(useValue('system.motion.spring')),damping:Number(useValue('system.motion.damping')),mass:Number(useValue('system.motion.mass')),magnetism:Number(useValue('system.motion.magnetism')),inertia:Number(useValue('system.motion.inertia')),response:Number(useValue('system.motion.response')),compression:Number(useValue('system.behavior.compression')),lift:Number(useValue('system.motion.lift')),tilt:Number(useValue('system.motion.tilt'))}}

function Stage({openEditor}:{openEditor:()=>void}){return <div className="studio-stage"><div className="studio-stage-image"/><div className="studio-stage-optics"/><BrandMark label="ARTINOS" onClick={openEditor}/><div className="stage-meta"><span>PROJECT</span><b>AURORA</b><span>·</span><span>LOCKED FULLSCREEN METABLOCK</span></div></div>}
function makeSectionWorkspace(page:StudioPageSpec){const nested=new MetaBlockWorkspace({id:`page-${page.id}`,historyLimit:80});page.sections.forEach((section,index)=>{const group=nested.createGroup({id:`${page.id}-section-${index}`,title:section.title,role:'group',posture:'docked',meta:{variant:'instrument-section',sectionIndex:index,contained:true,structural:true},capabilities:{closable:false,movable:false,resizable:false,floatable:false,dockable:false,splittable:false,tabbable:false,popoutable:false,maximizable:false,pinable:false,autoHideable:false,nestable:false,acceptsDrop:false}});nested.createMetaBlock({id:`${page.id}-section-block-${index}`,title:section.title,role:'panel',meta:{variant:'instrument',sectionIndex:index,contained:true},capabilities:{closable:false,movable:false,resizable:false,floatable:false,dockable:false,splittable:false,tabbable:false,popoutable:false,maximizable:false,pinable:false,autoHideable:false,nestable:false,acceptsDrop:false}},{groupId:group})});return nested}
function layoutForColumns(nested:MetaBlockWorkspace,page:StudioPageSpec,columns:number){const groups=page.sections.map((_,i)=>`${page.id}-section-${i}`),nodes:LayoutNode[]=[];if(groups.length===1)nodes.push({id:'center',groupId:groups[0],area:'center',targetGroupId:null,size:1,order:0});else if(columns>=3){nodes.push({id:'left',groupId:groups[0],area:'left',targetGroupId:null,size:.39,order:0},{id:'right',groupId:groups[2]??groups[1],area:'right',targetGroupId:null,size:.46,order:2},{id:'center',groupId:groups[1],area:'center',targetGroupId:null,size:1,order:1})}else if(columns===2){nodes.push({id:'left',groupId:groups[0],area:'left',targetGroupId:null,size:.5,order:0},{id:'top',groupId:groups[1],area:'top',targetGroupId:null,size:.5,order:1});if(groups[2])nodes.push({id:'center',groupId:groups[2],area:'center',targetGroupId:null,size:1,order:2})}else{nodes.push({id:'top',groupId:groups[0],area:'top',targetGroupId:null,size:.333,order:0});if(groups[1])nodes.push({id:'bottom',groupId:groups[1],area:'bottom',targetGroupId:null,size:.5,order:1});if(groups[2])nodes.push({id:'center',groupId:groups[2],area:'center',targetGroupId:null,size:1,order:2})}nested.setLayout(nodes,{history:false})}

function PageWorkspace({page,query}:{page:StudioPageSpec;query:string}){
  const nested=useMemo(()=>makeSectionWorkspace(page),[page.id]);const host=useRef<HTMLDivElement|null>(null),[width,setWidth]=useState(1200);const motion=useSpatialMotion();
  const forced=String(useValue('system.layout.dockColumns')),compactMode=String(useValue('system.layout.compactMode')),groupGap=Number(useValue('system.layout.groupGap'));
  const density=String(useValue('system.metacomp.density')).toLowerCase(),labelModeRaw=String(useValue('system.metacomp.labelMode')).toLowerCase();
  const labelMode=labelModeRaw==='context'?'contextual':labelModeRaw;
  useEffect(()=>{const node=host.current;if(!node)return;const update=()=>setWidth(node.clientWidth);update();const ro=new ResizeObserver(update);ro.observe(node);return()=>ro.disconnect()},[]);
  const autoColumns=compactMode==='FOCUS'&&width<620?1:width>900?3:width>580?2:1,columns=forced==='AUTO'?autoColumns:Number(forced);
  useEffect(()=>layoutForColumns(nested,page,columns),[nested,page.id,columns]);
  const context:MetaCompContext={density,width:Math.max(160,width/Math.max(1,columns)),labelMode};
  const renderBlock=(block:MetaBlockInstance,group:MetaBlockGroup)=>{const index=Number(block.meta?.sectionIndex??group.meta?.sectionIndex??0),section=page.sections[index];return <div className="instrument-content"><Inspector graph={graph} entries={section.entries} context={context}/></div>};
  const renderChrome=(ctx:GroupChromeContext)=>{const section=page.sections[Number(ctx.group.meta?.sectionIndex??0)];return <ChromeBar data-no-drag><PanelTitle>{section.title}</PanelTitle><ChromeFill/></ChromeBar>};
  const renderFooter=(group:MetaBlockGroup)=>{const section=page.sections[Number(group.meta?.sectionIndex??0)];return <StatusLine>{section.footer}</StatusLine>};
  const panelGap=Math.max(5,Math.min(10,groupGap));
  return <div ref={host} className="studio-nested-host" data-filtering={query?'true':'false'}><MetaBlockWorkspaceView workspace={nested} renderBlock={renderBlock} renderGroupChrome={renderChrome} renderGroupFooter={renderFooter} gap={panelGap} dockRadius={48} snap={10} dockRatio={.30} splitRatio={.36} motion={motion}/></div>
}

function QuickControls({openEditor}:{openEditor:()=>void}){return <div className="quick-content">{controlEntries(quickEntries).map(entry=><Control key={entry.id} parameter={entry.parameter as Parameter} context={{density:'micro',width:150,labelMode:'external'}}/>)}<Button onClick={openEditor}>OPEN SYSTEM EDITOR</Button><p className="quick-tip">Every visible surface is a MetaBlock. Drag a tab to detach that MetaBlock, then group, split, dock, snap or float it anywhere.</p></div>}

function MainChrome({ctx,search,setSearch}:{ctx:GroupChromeContext;search:string;setSearch:(v:string)=>void}){
  const tabs=<TabBar items={ctx.blocks.map(block=>({id:block.id,label:block.title.toUpperCase(),count:block.meta?.count}))} activeId={ctx.activeBlock?.id??null} onChange={ctx.activateBlock} getTabProps={item=>ctx.blockProps(item.id)}/>;
  if(ctx.group.role==='dock')return <ChromeBar {...ctx.dragHandleProps}>{tabs}<ChromeFill/><SearchBox value={search} onChange={setSearch} placeholder="Search project controls" shortcut="⌘K"/><TelemetryStrip items={[{label:'● WEBGPU',live:true},{label:'',value:'60 FPS'},{label:'CPU',value:'41'},{label:'GPU',value:'63'}]}/></ChromeBar>;
  if(ctx.group.meta?.variant==='quick-controls')return <ChromeBar {...ctx.dragHandleProps}><PanelTitle>WORKSPACE</PanelTitle><ChromeFill/></ChromeBar>;
  if(ctx.group.role==='panel'||ctx.group.meta?.extractedBlock===true)return <ChromeBar className="detached-panel-chrome" {...ctx.dragHandleProps}>{tabs}<ChromeFill/><span className="panel-posture">{String(ctx.group.posture).replace('-', ' ').toUpperCase()}</span></ChromeBar>;
  return <ChromeBar {...ctx.dragHandleProps}><PanelTitle>{ctx.group.title}</PanelTitle><ChromeFill/></ChromeBar>;
}

function renderMetaBlockContextMenu({model,close}:{model:any;close:()=>void}){
  return <ContextMenu title={model.title} subtitle={model.subtitle} meta={model.meta} sections={model.sections} onClose={close}/>
}

function RuntimeEffects({studioRef}:{studioRef:{current:HTMLDivElement|null}}){
  const world=String(useValue('system.world.world')).toLowerCase(),frost=Number(useValue('system.world.frost')),surface=Number(useValue('system.world.surface')),edge=Number(useValue('system.world.edge')),noise=Number(useValue('system.world.noise')),stage=Number(useValue('system.world.stage')),signal=String(useValue('system.world.signal'));
  const compHeight=Number(useValue('system.metacomp.height')),compRadius=Number(useValue('system.metacomp.radius')),seam=Number(useValue('system.metacomp.seam')),labelWidth=Number(useValue('system.metacomp.labelWidth')),rowGap=Number(useValue('system.metacomp.gap'));
  const blockRadius=Number(useValue('system.metablock.radius')),shellInset=Number(useValue('system.layout.shellInset')),groupInset=Number(useValue('system.layout.groupInset')),footer=Number(useValue('system.layout.footer')),chrome=String(useValue('system.layout.chrome')).toLowerCase();
  const proximity=Boolean(useValue('system.behavior.proximity')),precision=Number(useValue('system.behavior.precision')),offAxis=Number(useValue('system.behavior.offAxis')),compression=Number(useValue('system.behavior.compression')),expandedHits=Boolean(useValue('system.behavior.expandedHits'));
  const response=Number(useValue('system.motion.response')),profile=String(useValue('system.motion.profile')).toLowerCase(),magnetism=Number(useValue('system.motion.magnetism'));
  const quickPosition=String(useValue('quick.position')),quickSize=String(useValue('quick.size')),quickTheme=String(useValue('quick.theme')).toLowerCase(),dockSize=Number(useValue('system.metablock.dockSize'));
  const scale=Number(useValue('system.type.scale')),labelSize=Number(useValue('system.type.labelSize')),valueSize=Number(useValue('system.type.valueSize')),tracking=Number(useValue('system.type.tracking')),contrast=String(useValue('system.type.contrast')).toLowerCase();
  const reduced=Boolean(useValue('system.access.reducedMotion')),highContrast=Boolean(useValue('system.access.highContrast')),largeTargets=Boolean(useValue('system.access.largeTargets')),focusRing=String(useValue('system.access.focusRing')).toLowerCase();
  useEffect(()=>{const root=document.documentElement;applyTheme(root,world==='dark'?'graphite':world);root.style.setProperty('--au-frost',`blur(${frost}px) saturate(104%)`);root.style.setProperty('--au-control-edge',`rgba(255,255,255,${edge/100})`);root.style.setProperty('--au-material-noise',String(noise/100));root.style.setProperty('--au-signal',signal);root.style.setProperty('--au-signal-hi',signal);root.style.setProperty('--au-control-h',`${compHeight}px`);root.style.setProperty('--au-control-r',`${compRadius}px`);root.style.setProperty('--au-seam-w',`${seam}px`);root.style.setProperty('--au-label-w',`${labelWidth}%`);root.style.setProperty('--au-gap',`${rowGap}px`);root.style.setProperty('--au-ui-scale',String(scale/100));root.style.setProperty('--au-precision-factor',String(precision));root.style.setProperty('--au-offaxis-distance',String(offAxis));root.style.setProperty('--au-compression',String(compression));root.style.setProperty('--mb-motion',`${response}ms cubic-bezier(.2,.75,.2,1)`);root.style.setProperty('--mb-magnetism',String(magnetism))},[world,frost,edge,noise,signal,compHeight,compRadius,seam,labelWidth,rowGap,scale,precision,offAxis,compression,response,magnetism]);
  useEffect(()=>{const studio=studioRef.current;if(!studio)return;studio.style.setProperty('--stage-exposure',String(stage/100));studio.style.setProperty('--mb-radius',`${blockRadius}px`);studio.style.setProperty('--mb-surface-bg',`color-mix(in srgb,var(--au-surface) ${surface}%,transparent)`);studio.style.setProperty('--dock-group-inset',`${Math.max(10,groupInset)}px`);studio.style.setProperty('--mb-footer-opacity',String(footer/100));studio.style.setProperty('--studio-label-size',`${labelSize}px`);studio.style.setProperty('--studio-value-size',`${valueSize}px`);studio.style.setProperty('--studio-tracking',`${tracking}em`);studio.dataset.contrast=contrast;studio.dataset.chrome=chrome;studio.dataset.proximity=proximity?'true':'false';studio.dataset.motion=profile;studio.dataset.focus=focusRing;studio.classList.toggle('reduced-motion',reduced);studio.classList.toggle('high-contrast',highContrast);studio.classList.toggle('large-targets',largeTargets||expandedHits)},[stage,blockRadius,surface,groupInset,footer,labelSize,valueSize,tracking,contrast,chrome,proximity,profile,focusRing,reduced,highContrast,largeTargets,expandedHits]);
  useEffect(()=>{const mode=`${quickPosition.toLowerCase()}-dock`;const sideInset=quickPosition==='BOTTOM'?14:Math.max(12,shellInset),bottomInset=quickPosition==='BOTTOM'?7:Math.max(6,Math.round(sideInset*.5));workspace.setZoneMode(ids.dockGroup,mode);workspace.setGroupMeta(ids.dockGroup,{edgeInset:quickPosition==='BOTTOM'?{left:sideInset,right:sideInset,bottom:bottomInset,top:6}:{left:sideInset,right:sideInset,bottom:sideInset,top:sideInset}})},[quickPosition,shellInset]);
  useEffect(()=>{if(studioRef.current)studioRef.current.dataset.dockPosition=quickPosition.toLowerCase()},[quickPosition]);
  useEffect(()=>{const px={S:238,M:286,L:360}[quickSize]??dockSize,sideInset=quickPosition==='BOTTOM'?14:Math.max(12,shellInset),bottomInset=quickPosition==='BOTTOM'?7:Math.max(6,Math.round(sideInset*.5)),available=quickPosition==='BOTTOM'?innerHeight-6-bottomInset:innerWidth-sideInset*2,ratio=px/Math.max(1,available);workspace.setGroupMeta(ids.dockGroup,{zoneSize:Math.max(.12,Math.min(.48,ratio))})},[quickSize,dockSize,quickPosition,shellInset]);
  useEffect(()=>{if(quickTheme&&quickTheme!==world){const p=graph.get('system.world.world');if(p&&String(p.value).toLowerCase()!==quickTheme)p.set(quickTheme.toUpperCase(),{source:'system',history:false,force:true})}},[quickTheme,world]);
  return null;
}

export default function App(){
  const studioRef=useRef<HTMLDivElement|null>(null),[search,setSearch]=useState(''),[toast,setToast]=useState('');
  const blockGap=Number(useValue('system.metablock.gap')),dockRadius=Number(useValue('system.metablock.field')),snap=Number(useValue('system.metablock.snap')),dockRatio=Number(useValue('system.metablock.dockRatio')),splitRatio=Number(useValue('system.metablock.splitRatio')),hysteresis=Number(useValue('system.metablock.hysteresis')),intentHoldMs=Number(useValue('system.metablock.intentHold')),previewStrength=Number(useValue('system.metablock.previewStrength')),commitStrength=Number(useValue('system.metablock.commitStrength')),compass=Boolean(useValue('system.metablock.compass')),guides=Boolean(useValue('system.metablock.guides')),dragIntent=String(useValue('system.behavior.dragIntent'));const motion=useSpatialMotion();
  const openEditor=()=>window.open('./editor.html','artinos-system-editor','popup=yes,width=1320,height=880');
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),1200);return()=>clearTimeout(t)},[toast]);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();(document.querySelector('.au-search-box input') as HTMLInputElement|null)?.focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?graph.history.redo():graph.history.undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();graph.history.redo()}if(e.key.toLowerCase()==='e'&&!e.ctrlKey&&!e.metaKey&&!['INPUT','TEXTAREA','SELECT'].includes((document.activeElement as HTMLElement)?.tagName))openEditor()};addEventListener('keydown',onKey);return()=>removeEventListener('keydown',onKey)},[]);
  useEffect(()=>{const systemSync=syncParameterGraph(graph,{storageKey:SYSTEM_SETTINGS_STORAGE,channelName:SYSTEM_SETTINGS_CHANNEL,include:id=>id.startsWith('system.')});const appSync=syncParameterGraph(graph,{storageKey:'artinos.studio.parameters.v14',channelName:'artinos.studio.parameters.live.v14',include:id=>id.startsWith('page.')||id.startsWith('quick.')});const workspaceKey='artinos.studio.workspace.v14',saveWorkspace=()=>{try{localStorage.setItem(workspaceKey,JSON.stringify(workspace.serialize()))}catch{}},offWorkspace=workspace.on('*',saveWorkspace);try{const saved=JSON.parse(localStorage.getItem(workspaceKey)||'null');if(saved)workspace.restore(saved)}catch{}return()=>{systemSync.dispose();appSync.dispose();offWorkspace()}},[]);
  const renderBlock=(block:MetaBlockInstance)=>{if(block.id==='viewport')return <Stage openEditor={openEditor}/>;if(pageSpecs[block.id])return <PageWorkspace page={pageSpecs[block.id]} query={search}/>;if(block.id==='quick-tools-panel')return <QuickControls openEditor={openEditor}/>;return null};
  const renderChrome=(ctx:GroupChromeContext)=><MainChrome ctx={ctx} search={search} setSearch={setSearch}/>;
  const effectiveRadius=dragIntent==='FREE'?0:dockRadius*(.55+.45*(motion.magnetism??.72)),liveDocking=dragIntent!=='FREE';
  return <div ref={studioRef} className="studio" data-contrast="standard"><RuntimeEffects studioRef={studioRef}/><div className="studio-workspace"><MetaBlockWorkspaceView workspace={workspace} renderBlock={renderBlock} renderGroupChrome={renderChrome} renderContextMenu={renderMetaBlockContextMenu} gap={blockGap} dockRadius={effectiveRadius} snap={snap} dockRatio={dockRatio} splitRatio={splitRatio} hysteresis={hysteresis} intentHoldMs={intentHoldMs} previewStrength={previewStrength} commitStrength={commitStrength} liveDocking={liveDocking} showDockCompass={compass} showSmartGuides={guides} motion={motion} onEvent={event=>{if(event.type==='drop')setToast(event.kind==='block'?'METABLOCK PLACED':event.candidate?.kind?.toUpperCase()??'FLOAT')}}/></div><div className={`toast ${toast?'show':''}`}>{toast}</div></div>
}
