import { useEffect, useMemo, useRef, useState } from 'react';
import {
  applyTheme, BrandMark, Button, ChromeBar, ChromeFill, Control, defineControls, Inspector, PanelTitle, ParameterGraph,
  StatusLine, syncParameterGraph, type MetaCompContext, type Parameter
} from '@artinos/ui';
import { MetaBlendPreview, MetaBlockWorkspace, MetaBlockWorkspaceView, type GroupChromeContext, type MetaBlockGroup, type MetaBlockInstance, type MetaBlockMotionConfig } from '@artinos/metablock';
import { applySystemPreset, defineSystemSettings, SYSTEM_SETTINGS_CHANNEL, SYSTEM_SETTINGS_STORAGE, systemEditorPages, systemPresets } from '../../shared/system-schema.js';

const graph=new ParameterGraph({historyLimit:600});
const entries=defineSystemSettings(graph);
const preset=graph.define({id:'editor.preset',value:'Precision Glass',options:Object.keys(systemPresets),presentation:'select',label:'Preset',persistent:false});
const previewEntries=defineControls(graph,{previewAmount:{value:.58,min:0,max:1,step:.01,label:'Surface control',ticks:7,persistent:false},previewRange:{value:[.2,.76],type:'range',min:0,max:1,step:.01,label:'Range',persistent:false},previewMode:{value:'B',options:['A','B','C'],presentation:'segmented',label:'Mode',persistent:false},previewToggle:{value:true,label:'Enabled',persistent:false}},{prefix:'editor.preview'});

function useGraphValue<T=any>(id:string){const p=graph.get<T>(id);const[,tick]=useState(0);useEffect(()=>p?.subscribe(()=>tick(v=>v+1)),[p]);return p?.value as T}
function useEditorMotion():Partial<MetaBlockMotionConfig>{return{profile:String(useGraphValue('system.motion.profile')??'PHYSICAL').toLowerCase(),stiffness:Number(useGraphValue('system.motion.spring')??280),damping:Number(useGraphValue('system.motion.damping')??28),mass:Number(useGraphValue('system.motion.mass')??1),magnetism:Number(useGraphValue('system.motion.magnetism')??.72),inertia:Number(useGraphValue('system.motion.inertia')??.38),response:Number(useGraphValue('system.motion.response')??220),compression:Number(useGraphValue('system.behavior.compression')??.012),lift:Number(useGraphValue('system.motion.lift')??5),tilt:Number(useGraphValue('system.motion.tilt')??1.15)}}

function createEditorWorkspace(){
  const ws=new MetaBlockWorkspace({id:'artinos-system-editor',historyLimit:260});
  const base=ws.createGroup({id:'editor-base',title:'Editor Base',role:'viewport',posture:'fullscreen-locked',lockedFullscreen:true,meta:{variant:'editor-base'}});ws.createMetaBlock({id:'editor-background',title:'System Editor',role:'viewport',meta:{variant:'editor-background'}},{groupId:base});
  const toolbar=ws.createGroup({id:'editor-toolbar',title:'System Toolbar',role:'toolbar',posture:'docked',meta:{variant:'editor-toolbar'},capabilities:{closable:false,floatable:false,resizable:false,popoutable:false,maximizable:false}});ws.createMetaBlock({id:'editor-toolbar-panel',title:'ARTINOS System Editor',role:'toolbar'},{groupId:toolbar});ws.dockGroup(toolbar,{area:'top',size:.075,order:0});
  const nav=ws.createGroup({id:'editor-nav',title:'System Navigation',role:'sidebar',posture:'docked',meta:{variant:'editor-nav'},capabilities:{closable:false,popoutable:false,maximizable:false}});ws.createMetaBlock({id:'editor-nav-panel',title:'SYSTEM',role:'panel',meta:{variant:'navigation'}},{groupId:nav});ws.dockGroup(nav,{area:'left',size:.17,order:1});
  const preview=ws.createGroup({id:'editor-preview',title:'Live Preview',role:'panel',posture:'docked',meta:{variant:'editor-preview'},capabilities:{closable:false,popoutable:false,maximizable:false}});ws.createMetaBlock({id:'editor-preview-panel',title:'LIVE PREVIEW',role:'panel',meta:{variant:'preview'}},{groupId:preview});ws.dockGroup(preview,{area:'right',size:.28,order:2});
  const content=ws.createGroup({id:'editor-content',title:'Settings',role:'dock',posture:'docked',meta:{variant:'editor-content',allowRootCenter:true},capabilities:{closable:false,popoutable:false,maximizable:true}});for(const[id,label,description]of systemEditorPages)ws.createMetaBlock({id:`settings-${id}`,title:label,role:'panel',meta:{variant:'settings',page:id,description}},{groupId:content});ws.dockGroup(content,{area:'center',order:3});ws.activateBlock('settings-world');
  return ws;
}
const workspace=createEditorWorkspace();

function createPreviewWorkspace(){const ws=new MetaBlockWorkspace({id:'editor-live-preview',historyLimit:40});const group=ws.createGroup({id:'preview-material-group',title:'Material',role:'panel',posture:'docked',meta:{variant:'preview-surface',allowRootCenter:true},capabilities:{closable:false,popoutable:false,maximizable:false}});ws.createMetaBlock({id:'preview-material',title:'MATERIAL',role:'panel',meta:{variant:'preview-material'}},{groupId:group});return ws}

function Background(){return <div className="editor-background"><div className="editor-grid"/><div className="editor-orb"/></div>}
function Nav(){return <div className="editor-nav-list">{systemEditorPages.map(([id,label,description])=><Button key={id} className="editor-nav-button" onClick={()=>workspace.activateBlock(`settings-${id}`)}><span>{label}</span><small>{description}</small></Button>)}</div>}
function SettingsPage({block}:{block:MetaBlockInstance}){const page=String(block.meta?.page??'world'),description=String(block.meta?.description??'');const density=String(useGraphValue('system.metacomp.density')??'COMPACT').toLowerCase(),labelModeRaw=String(useGraphValue('system.metacomp.labelMode')??'EXTERNAL').toLowerCase();const context:MetaCompContext={density,labelMode:labelModeRaw==='context'?'contextual':labelModeRaw,width:520};return <div className="editor-settings-page"><div className="editor-page-intro"><span>ARTINOS / {block.title}</span><h1>{block.title}</h1><p>{description}. Every setting is a real system Parameter; changes are broadcast, persisted and applied to MetaBlock/UI renderers live.</p></div><Inspector graph={graph} entries={entries[page]??[]} context={context}/>{page==='metablock'?<MetaBlendPreview strength={Number(graph.get('system.metablock.blend')?.value??.62)}/>:null}</div>}
function Preview(){const density=String(useGraphValue('system.metacomp.density')??'COMPACT').toLowerCase(),labelModeRaw=String(useGraphValue('system.metacomp.labelMode')??'EXTERNAL').toLowerCase(),gap=Number(useGraphValue('system.metablock.gap')??8),dockRadius=Number(useGraphValue('system.metablock.field')??72),snap=Number(useGraphValue('system.metablock.snap')??14),blend=Number(useGraphValue('system.metablock.blend')??.62);const motion=useEditorMotion();const previewWorkspace=useMemo(()=>createPreviewWorkspace(),[]);const renderBlock=()=> <div className="preview-package-content"><Inspector graph={graph} entries={previewEntries} context={{density,labelMode:labelModeRaw==='context'?'contextual':labelModeRaw,width:320}}/><MetaBlendPreview strength={blend}/></div>;const chrome=(ctx:GroupChromeContext)=><ChromeBar {...ctx.dragHandleProps}><PanelTitle>MATERIAL</PanelTitle><ChromeFill/><span className="editor-drag-mark">LIVE METABLOCK</span></ChromeBar>;return <div className="editor-preview-content"><div className="preview-caption"><span>LIVE PACKAGE OUTPUT</span><b>@artinos/ui + @artinos/metablock</b></div><div className="editor-preview-workspace"><MetaBlockWorkspaceView workspace={previewWorkspace} renderBlock={renderBlock} renderGroupChrome={chrome} gap={gap} dockRadius={dockRadius} snap={snap} motion={motion}/></div><StatusLine><span>LIVE</span><span>Changes broadcast to Studio</span></StatusLine></div>}

function Toolbar({save,reset,exportConfig}:{save:()=>void;reset:()=>void;exportConfig:()=>void}){return <ChromeBar><BrandMark label="ARTINOS SYSTEM EDITOR"/><ChromeFill/><div className="editor-preset"><Control parameter={preset as Parameter} context={{density:'micro',width:190,labelMode:'external'}}/></div><Button onClick={()=>applySystemPreset(graph,preset.value as keyof typeof systemPresets)}>APPLY PRESET</Button><Button onClick={save}>SAVE</Button><Button onClick={exportConfig}>EXPORT</Button><Button onClick={reset}>RESET</Button></ChromeBar>}

function applyRuntime(root:HTMLElement|null){if(!root)return;const world=String(graph.get('system.world.world')?.value??'GLASS').toLowerCase();applyTheme(document.documentElement,world==='dark'?'graphite':world);const set=(name:string,value:any)=>document.documentElement.style.setProperty(name,String(value));set('--au-frost',`blur(${graph.get('system.world.frost')?.value??42}px) saturate(104%)`);set('--au-control-h',`${graph.get('system.metacomp.height')?.value??28}px`);set('--au-control-r',`${graph.get('system.metacomp.radius')?.value??8}px`);set('--au-seam-w',`${graph.get('system.metacomp.seam')?.value??1}px`);set('--au-label-w',`${graph.get('system.metacomp.labelWidth')?.value??39}%`);set('--au-gap',`${graph.get('system.metacomp.gap')?.value??6}px`);set('--au-signal',graph.get('system.world.signal')?.value??'#2fb39c');set('--au-signal-hi',graph.get('system.world.signal')?.value??'#2fb39c');set('--au-precision-factor',graph.get('system.behavior.precision')?.value??.16);set('--au-offaxis-distance',`${graph.get('system.behavior.offAxis')?.value??42}`);set('--au-compression',graph.get('system.behavior.compression')?.value??.012);root.style.setProperty('--mb-radius',`${graph.get('system.metablock.radius')?.value??12}px`);root.style.setProperty('--editor-inset',`${graph.get('system.layout.groupInset')?.value??9}px`);root.dataset.contrast=String(graph.get('system.type.contrast')?.value??'STANDARD').toLowerCase();root.classList.toggle('high-contrast',Boolean(graph.get('system.access.highContrast')?.value));root.classList.toggle('reduced-motion',Boolean(graph.get('system.access.reducedMotion')?.value))}

export default function EditorApp(){
  const rootRef=useRef<HTMLDivElement|null>(null),syncRef=useRef<ReturnType<typeof syncParameterGraph>|null>(null),[saved,setSaved]=useState('AUTO-SAVED');
  const gap=Number(useGraphValue('system.metablock.gap')??8),dockRadius=Number(useGraphValue('system.metablock.field')??72),snap=Number(useGraphValue('system.metablock.snap')??14),dockRatio=Number(useGraphValue('system.metablock.dockRatio')??.28),splitRatio=Number(useGraphValue('system.metablock.splitRatio')??.36),hysteresis=Number(useGraphValue('system.metablock.hysteresis')??.16),intentHoldMs=Number(useGraphValue('system.metablock.intentHold')??92),previewStrength=Number(useGraphValue('system.metablock.previewStrength')??.30),commitStrength=Number(useGraphValue('system.metablock.commitStrength')??.54),compass=Boolean(useGraphValue('system.metablock.compass')),guides=Boolean(useGraphValue('system.metablock.guides'));const motion=useEditorMotion();
  useEffect(()=>{syncRef.current=syncParameterGraph(graph,{storageKey:SYSTEM_SETTINGS_STORAGE,channelName:SYSTEM_SETTINGS_CHANNEL,include:id=>id.startsWith('system.')});const off=graph.events.on('parameter:change',()=>{applyRuntime(rootRef.current);setSaved('LIVE · UNSAVED');setTimeout(()=>setSaved('AUTO-SAVED'),180)});applyRuntime(rootRef.current);return()=>{off();syncRef.current?.dispose()}},[]);
  const save=()=>{syncRef.current?.save();setSaved('SAVED · BROADCAST')};
  const reset=()=>{graph.transaction('Reset ARTINOS system',()=>{for(const p of graph.parameters.values())if(p.id.startsWith('system.'))p.reset({history:false,source:'system',force:true})});syncRef.current?.save();setSaved('RESET · SAVED')};
  const exportConfig=()=>{const blob=new Blob([JSON.stringify(syncRef.current?.snapshot()??graph.serialize(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='artinos-system-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);setSaved('EXPORTED')};
  const renderBlock=(block:MetaBlockInstance)=>{if(block.id==='editor-background')return <Background/>;if(block.id==='editor-toolbar-panel')return <Toolbar save={save} reset={reset} exportConfig={exportConfig}/>;if(block.id==='editor-nav-panel')return <Nav/>;if(block.id==='editor-preview-panel')return <Preview/>;if(block.meta?.variant==='settings')return <SettingsPage block={block}/>;return null};
  const renderChrome=(ctx:GroupChromeContext)=>{if(ctx.group.role==='toolbar'||ctx.group.lockedFullscreen)return null;if(ctx.group.meta?.variant==='editor-content')return <ChromeBar {...ctx.dragHandleProps}><PanelTitle>{ctx.activeBlock?.title??'SYSTEM'}</PanelTitle><ChromeFill/><span className="editor-saved-state">{saved}</span></ChromeBar>;return <ChromeBar {...ctx.dragHandleProps}><PanelTitle>{ctx.activeBlock?.title??ctx.group.title}</PanelTitle><ChromeFill/><span className="editor-drag-mark">MOVE METABLOCK</span></ChromeBar>};
  return <div ref={rootRef} className="system-editor-app"><MetaBlockWorkspaceView workspace={workspace} renderBlock={renderBlock} renderGroupChrome={renderChrome} gap={gap} dockRadius={dockRadius} snap={snap} dockRatio={dockRatio} splitRatio={splitRatio} hysteresis={hysteresis} intentHoldMs={intentHoldMs} previewStrength={previewStrength} commitStrength={commitStrength} showDockCompass={compass} showSmartGuides={guides} motion={motion}/></div>
}
